-- Hihibel — Supabase Schema
-- Jalankan di Supabase Dashboard → SQL Editor

-- Tabel soal
CREATE TABLE IF NOT EXISTS soal (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sub_bab    TEXT NOT NULL DEFAULT 'kecepatan',
  kategori   TEXT NOT NULL,
  soal       TEXT NOT NULL,
  opsi       JSONB NOT NULL,
  jawaban    TEXT NOT NULL CHECK (jawaban IN ('A','B','C','D','E')),
  langkah    JSONB NOT NULL DEFAULT '[]',
  animasi    JSONB,
  urutan     INT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_soal_sub_bab ON soal(sub_bab);
CREATE INDEX IF NOT EXISTS idx_soal_kategori ON soal(kategori);

-- Auto-update updated_at
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS soal_updated_at ON soal;
CREATE TRIGGER soal_updated_at
  BEFORE UPDATE ON soal
  FOR EACH ROW EXECUTE FUNCTION update_updated_at();

-- Row Level Security
ALTER TABLE soal ENABLE ROW LEVEL SECURITY;

-- Member login: baca soal (bukan publik)
DROP POLICY IF EXISTS "soal_public_read" ON soal;
DROP POLICY IF EXISTS "soal_member_read" ON soal;
CREATE POLICY "soal_member_read" ON soal
  FOR SELECT TO authenticated USING (true);

-- Admin (user login): tulis soal
DROP POLICY IF EXISTS "soal_admin_insert" ON soal;
CREATE POLICY "soal_admin_insert" ON soal
  FOR INSERT TO authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "soal_admin_update" ON soal;
CREATE POLICY "soal_admin_update" ON soal
  FOR UPDATE TO authenticated USING (true);

DROP POLICY IF EXISTS "soal_admin_delete" ON soal;
CREATE POLICY "soal_admin_delete" ON soal
  FOR DELETE TO authenticated USING (true);

-- Opsional: batasi hanya email admin tertentu (ganti email kamu)
-- DROP POLICY IF EXISTS "soal_admin_insert" ON soal;
-- CREATE POLICY "soal_admin_insert" ON soal
--   FOR INSERT TO authenticated
--   WITH CHECK (auth.jwt() ->> 'email' = 'email-kamu@gmail.com');
